"""
AegisBurn AI -- Drift Prediction Evaluation Harness
=======================================================

Solves the remaining evaluation gap for Module B:

    "Drift Prediction Accuracy: The mean absolute error between
    the predicted Value_168h and the actual hidden ground-truth
    values."

Reuses the SAME held-out labeled dataset generated by
evaluate_anomaly.py (src/data/eval/held_out_labeled.csv, seed
distinct from production) so this MAE/RMSE/R2 is measured on data
the prediction models have genuinely never seen -- not just an
internal train/test split of the training set.

USAGE:

    python evaluate_drift.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))

from src.drift_prediction import PredictionModelRegistry
from src.data_generator import generate_dataset


EVAL_SEED = 20260913

EVAL_DATA_PATH = Path(
    "src/data/eval/held_out_labeled.csv"
)

MODEL_DIR = Path("models/prediction")


def get_eval_dataset() -> pd.DataFrame:

    if EVAL_DATA_PATH.exists():

        print(
            f"Loading cached held-out evaluation set: "
            f"{EVAL_DATA_PATH}"
        )

        return pd.read_csv(EVAL_DATA_PATH)

    print(
        "Generating held-out evaluation set "
        f"(seed={EVAL_SEED})..."
    )

    df = generate_dataset(seed=EVAL_SEED)

    EVAL_DATA_PATH.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    df.to_csv(EVAL_DATA_PATH, index=False)

    return df


def main() -> None:

    eval_df = get_eval_dataset()

    print()
    print("=" * 78)
    print(
        f"HELD-OUT EVALUATION SET: {len(eval_df):,} components "
        f"(seed={EVAL_SEED})"
    )
    print("=" * 78)

    if not MODEL_DIR.exists():

        print(
            f"\nERROR: no trained prediction models found at "
            f"{MODEL_DIR}. Run 'python train_drift.py' first."
        )

        return

    registry = PredictionModelRegistry.load(MODEL_DIR)

    overall_errors = []
    overall_true = []
    overall_pred = []

    print()

    for key, predictor in registry.models.items():

        component_type, parameter_name = key.split(
            "__",
            1,
        )

        family_df = eval_df[
            (eval_df["component_type"] == component_type)
            & (eval_df["parameter_name"] == parameter_name)
        ]

        predictions = []

        for _, row in family_df.iterrows():

            # Only early measurements are passed in -- the
            # registry's predict_component ignores value_168h
            # even if present, but this makes the "never touches
            # ground truth" guarantee explicit here too.
            model_input = pd.Series(
                {
                    "component_id": row["component_id"],
                    "component_type": row["component_type"],
                    "parameter_name": row["parameter_name"],
                    "value_0h": row["value_0h"],
                    "value_24h": row["value_24h"],
                    "value_96h": row["value_96h"],
                }
            )

            result = registry.predict_component(
                model_input
            )

            predictions.append(
                result.predicted_168h
            )

        y_true = family_df["value_168h"].to_numpy()
        y_pred = np.array(predictions)

        errors = np.abs(y_true - y_pred)

        mae = errors.mean()
        rmse = np.sqrt(
            np.mean((y_true - y_pred) ** 2)
        )

        ss_res = np.sum((y_true - y_pred) ** 2)
        ss_tot = np.sum(
            (y_true - y_true.mean()) ** 2
        )

        r2 = (
            1 - ss_res / ss_tot
            if ss_tot > 0
            else float("nan")
        )

        print(
            f"{component_type} / {parameter_name} "
            f"(n={len(family_df)}):"
        )

        print(
            f"  MAE:  {mae:.4f}"
        )

        print(
            f"  RMSE: {rmse:.4f}"
        )

        print(
            f"  R2:   {r2:.4f}"
        )

        print()

        overall_errors.append(errors)
        overall_true.append(y_true)
        overall_pred.append(y_pred)

    overall_errors = np.concatenate(overall_errors)
    overall_true = np.concatenate(overall_true)
    overall_pred = np.concatenate(overall_pred)

    overall_mae = overall_errors.mean()
    overall_rmse = np.sqrt(
        np.mean((overall_true - overall_pred) ** 2)
    )

    print("=" * 78)
    print("OVERALL (ALL FAMILIES, HELD-OUT SET)")
    print("=" * 78)
    print(f"MAE:  {overall_mae:.4f}")
    print(f"RMSE: {overall_rmse:.4f}")


if __name__ == "__main__":
    main()